-- data_set_spec.lua

local busted = require("busted")
local assert = require("luassert")

local lfs = require("lfs")

local describe = busted.describe
local it = busted.it
local before_each = busted.before_each
local after_each = busted.after_each

local file_util = require("file_util")
local data_set = require("data_set")

local function path_join(...)
    return (table.concat({...}, "/"):gsub("//+", "/"))
end

--- Write a TSV string to a file in the temp directory.
local function writeTestFile(dir, fileName, content)
    local fullPath = path_join(dir, fileName)
    local parent = fullPath:match("^(.+)/")
    if parent then
        file_util.mkdir(parent)
    end
    assert(file_util.writeFile(fullPath, content))
end

--- Read a file and return its content.
local function readTestFile(dir, fileName)
    local fullPath = path_join(dir, fileName)
    local content, err = file_util.readFile(fullPath)
    return content, err
end

--- Check if a file exists on disk.
local function fileExists(path)
    local f = io.open(path, "r")
    if f then
        f:close()
        return true
    end
    return false
end

describe("data_set", function()
    local temp_dir

    before_each(function()
        local system_temp = file_util.getSystemTempDir()
        assert(system_temp ~= nil and system_temp ~= "", "Could not find system temp directory")
        local td = path_join(system_temp, "lua_data_set_test_" .. os.time())
        assert(lfs.mkdir(td))
        temp_dir = td
    end)

    after_each(function()
        if temp_dir then
            local td = temp_dir
            temp_dir = nil
            file_util.deleteTempDir(td)
        end
    end)

    ---------------------------------------------------------------------------
    -- Module API
    ---------------------------------------------------------------------------

    describe("module API", function()
        it("should return a version string", function()
            local version = data_set.getVersion()
            assert.is_string(version)
            assert.matches("^%d+%.%d+%.%d+$", version)
        end)

        it("should have __tostring", function()
            local str = tostring(data_set)
            assert.is_string(str)
            assert.matches("^data_set version %d+%.%d+%.%d+$", str)
        end)

        it("should be callable with 'version'", function()
            local version = data_set("version")
            assert.is_not_nil(version)
        end)

        it("should be callable with 'new'", function()
            local ds = data_set("new", temp_dir)
            assert.is_not_nil(ds)
        end)
    end)

    ---------------------------------------------------------------------------
    -- Constructor
    ---------------------------------------------------------------------------

    describe("new", function()
        it("should create a DataSet with a root directory", function()
            local ds = data_set.new(temp_dir)
            assert.is_not_nil(ds)
        end)

        it("should error on non-string rootDir", function()
            assert.has_error(function()
                data_set.new(123)
            end)
        end)
    end)

    ---------------------------------------------------------------------------
    -- File operations
    ---------------------------------------------------------------------------

    describe("loadFile", function()
        it("should load a TSV file", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\nbeta\t2\n")
            local ds = data_set.new(temp_dir)
            local ok, err = ds:loadFile("test.tsv")
            assert.is_true(ok)
            assert.is_nil(err)
            assert.is_true(ds:hasFile("test.tsv"))
        end)

        it("should parse column headers", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tparent:type_spec|nil\tdesc:text\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "parent", "desc"}, names)
        end)

        it("should error on non-existent file", function()
            local ds = data_set.new(temp_dir)
            local ok, err = ds:loadFile("nonexistent.tsv")
            assert.is_nil(ok)
            assert.is_not_nil(err)
        end)

        it("should error on duplicate load", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:loadFile("test.tsv")
            assert.is_nil(ok)
            assert.matches("already loaded", err)
        end)

        it("should error on file with no data rows (no header)", function()
            writeTestFile(temp_dir, "test.tsv", "# just a comment\n")
            local ds = data_set.new(temp_dir)
            local ok, err = ds:loadFile("test.tsv")
            assert.is_nil(ok)
            assert.matches("no header", err)
        end)

        it("should handle files with comments and blank lines", function()
            writeTestFile(temp_dir, "test.tsv",
                "# preamble\n\nname:string\tvalue:number\n# section\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            local ok = ds:loadFile("test.tsv")
            assert.is_true(ok)
            local names = ds:getColumnNames("test.tsv")
            assert.same({"name", "value"}, names)
            assert.are.equal(1, ds:rowCount("test.tsv"))
        end)

        it("should load files in subdirectories", function()
            writeTestFile(temp_dir, "sub/dir/test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            local ok = ds:loadFile("sub/dir/test.tsv")
            assert.is_true(ok)
        end)
    end)

    describe("loadTransposedFile", function()
        it("should load and transpose a file", function()
            -- Transposed: each row becomes a column
            writeTestFile(temp_dir, "manifest.tsv", "key:string\tvalue:string\npackage_id\tmy_pkg\nversion\t1.0.0\n")
            local ds = data_set.new(temp_dir)
            local ok = ds:loadTransposedFile("manifest.tsv")
            assert.is_true(ok)
            assert.is_true(ds:hasFile("manifest.tsv"))
        end)
    end)

    describe("saveFile", function()
        it("should save a file to disk", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:setCell("test.tsv", "alpha", "value", "99")
            local ok = ds:saveFile("test.tsv")
            assert.is_true(ok)
            local content = readTestFile(temp_dir, "test.tsv")
            assert.is_not_nil(content)
            assert.matches("99", content)
        end)

        it("should clear dirty flag after save", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:setCell("test.tsv", "alpha", "name", "beta")
            assert.is_true(ds:isDirty("test.tsv"))
            ds:saveFile("test.tsv")
            assert.is_false(ds:isDirty("test.tsv"))
        end)

        it("should create parent directories", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:renameFile("test.tsv", "deep/nested/dir/test.tsv")
            local ok = ds:saveFile("deep/nested/dir/test.tsv")
            assert.is_true(ok)
            assert.is_true(fileExists(path_join(temp_dir, "deep/nested/dir/test.tsv")))
        end)
    end)

    describe("saveAll", function()
        it("should save only dirty files", function()
            writeTestFile(temp_dir, "a.tsv", "name:string\nalpha\n")
            writeTestFile(temp_dir, "b.tsv", "name:string\nbeta\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("a.tsv")
            ds:loadFile("b.tsv")
            ds:setCell("a.tsv", "alpha", "name", "modified")
            assert.is_true(ds:isDirty("a.tsv"))
            assert.is_false(ds:isDirty("b.tsv"))
            local ok = ds:saveAll()
            assert.is_true(ok)
            assert.is_false(ds:isDirty("a.tsv"))
        end)
    end)

    describe("createFile", function()
        it("should create a new file in the dataset", function()
            local ds = data_set.new(temp_dir)
            local ok = ds:createFile("new.tsv", {"id:string", "name:string", "value:number"})
            assert.is_true(ok)
            assert.is_true(ds:hasFile("new.tsv"))
            local names = ds:getColumnNames("new.tsv")
            assert.same({"id", "name", "value"}, names)
            assert.is_true(ds:isDirty("new.tsv"))
        end)

        it("should accept pipe-delimited column specs", function()
            local ds = data_set.new(temp_dir)
            local ok = ds:createFile("new.tsv", "id:string|name:string|value:number")
            assert.is_true(ok)
            local names = ds:getColumnNames("new.tsv")
            assert.same({"id", "name", "value"}, names)
        end)

        it("should error on duplicate file name", function()
            local ds = data_set.new(temp_dir)
            ds:createFile("new.tsv", {"id:string"})
            local ok, err = ds:createFile("new.tsv", {"id:string"})
            assert.is_nil(ok)
            assert.matches("already exists", err)
        end)

        it("should save created file to disk", function()
            local ds = data_set.new(temp_dir)
            ds:createFile("new.tsv", {"id:string", "name:string"})
            ds:addRow("new.tsv", {"a1", "Alice"})
            ds:saveFile("new.tsv")
            local content = readTestFile(temp_dir, "new.tsv")
            assert.is_not_nil(content)
            assert.matches("id:string", content)
            assert.matches("Alice", content)
        end)
    end)

    describe("deleteFile", function()
        it("should remove file from dataset and disk", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:deleteFile("test.tsv")
            assert.is_true(ok)
            assert.is_false(ds:hasFile("test.tsv"))
            assert.is_false(fileExists(path_join(temp_dir, "test.tsv")))
        end)

        it("should handle file not on disk (created but never saved)", function()
            local ds = data_set.new(temp_dir)
            ds:createFile("new.tsv", {"id:string"})
            local ok = ds:deleteFile("new.tsv")
            assert.is_true(ok)
            assert.is_false(ds:hasFile("new.tsv"))
        end)
    end)

    describe("renameFile", function()
        it("should rename a file in the dataset", function()
            writeTestFile(temp_dir, "old.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("old.tsv")
            local ok = ds:renameFile("old.tsv", "new.tsv")
            assert.is_true(ok)
            assert.is_false(ds:hasFile("old.tsv"))
            assert.is_true(ds:hasFile("new.tsv"))
            assert.is_true(ds:isDirty("new.tsv"))
        end)

        it("should error on rename to existing file", function()
            writeTestFile(temp_dir, "a.tsv", "name:string\nalpha\n")
            writeTestFile(temp_dir, "b.tsv", "name:string\nbeta\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("a.tsv")
            ds:loadFile("b.tsv")
            local ok, err = ds:renameFile("a.tsv", "b.tsv")
            assert.is_nil(ok)
            assert.matches("already exists", err)
        end)

        it("should write to new path on save and delete old file", function()
            writeTestFile(temp_dir, "old.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("old.tsv")
            ds:renameFile("old.tsv", "sub/new.tsv")
            ds:saveFile("sub/new.tsv")
            assert.is_true(fileExists(path_join(temp_dir, "sub/new.tsv")))
            assert.is_false(fileExists(path_join(temp_dir, "old.tsv")))
        end)
    end)

    describe("copyFile", function()
        it("should create an independent copy", function()
            writeTestFile(temp_dir, "src.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("src.tsv")
            local ok = ds:copyFile("src.tsv", "dst.tsv")
            assert.is_true(ok)
            assert.is_true(ds:hasFile("dst.tsv"))
            -- Modify copy, original should be unaffected
            ds:setCell("dst.tsv", "alpha", "value", "99")
            assert.are.equal("1", ds:getCell("src.tsv", "alpha", "value"))
            assert.are.equal("99", ds:getCell("dst.tsv", "alpha", "value"))
        end)
    end)

    describe("listFiles", function()
        it("should return sorted list of file names", function()
            writeTestFile(temp_dir, "b.tsv", "name:string\nbeta\n")
            writeTestFile(temp_dir, "a.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("b.tsv")
            ds:loadFile("a.tsv")
            local files = ds:listFiles()
            assert.same({"a.tsv", "b.tsv"}, files)
        end)
    end)

    describe("hasFile / getFile / isDirty", function()
        it("should report correct state", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            assert.is_false(ds:hasFile("test.tsv"))
            ds:loadFile("test.tsv")
            assert.is_true(ds:hasFile("test.tsv"))
            assert.is_false(ds:isDirty("test.tsv"))
            local raw = ds:getFile("test.tsv")
            assert.is_table(raw)
        end)
    end)

    ---------------------------------------------------------------------------
    -- Column operations
    ---------------------------------------------------------------------------

    describe("getColumnNames", function()
        it("should return ordered column names", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\tvalue:number\nalpha\tAlice\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "name", "value"}, names)
        end)
    end)

    describe("hasColumn / getColumnIndex / getColumnSpec", function()
        it("should report column existence and info", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.is_true(ds:hasColumn("test.tsv", "id"))
            assert.is_true(ds:hasColumn("test.tsv", "name"))
            assert.is_false(ds:hasColumn("test.tsv", "missing"))
            assert.are.equal(1, ds:getColumnIndex("test.tsv", "id"))
            assert.are.equal(2, ds:getColumnIndex("test.tsv", "name"))
            assert.are.equal("id:string", ds:getColumnSpec("test.tsv", "id"))
        end)
    end)

    describe("addColumn", function()
        it("should append a column at the end by default", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\nbeta\tBob\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:addColumn("test.tsv", "score:number")
            assert.is_true(ok)
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "name", "score"}, names)
            -- Data rows should have empty cell
            assert.are.equal("", ds:getCell("test.tsv", "alpha", "score"))
            assert.is_true(ds:isDirty("test.tsv"))
        end)

        it("should insert after a named column", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addColumn("test.tsv", "parent:type_spec|nil", {after = "id"})
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "parent", "name"}, names)
        end)

        it("should insert before a named column", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addColumn("test.tsv", "parent:type_spec|nil", {before = "name"})
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "parent", "name"}, names)
        end)

        it("should insert at a specific index", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addColumn("test.tsv", "rank:number", {index = 1})
            local names = ds:getColumnNames("test.tsv")
            assert.same({"rank", "id", "name"}, names)
        end)

        it("should error on duplicate column name", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:addColumn("test.tsv", "name:number")
            assert.is_nil(ok)
            assert.matches("already exists", err)
        end)
    end)

    describe("removeColumn", function()
        it("should remove a column and its data", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\tvalue:number\nalpha\tAlice\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:removeColumn("test.tsv", "name")
            assert.is_true(ok)
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "value"}, names)
            assert.are.equal("1", ds:getCell("test.tsv", "alpha", "value"))
            assert.is_true(ds:isDirty("test.tsv"))
        end)

        it("should error on non-existent column", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:removeColumn("test.tsv", "missing")
            assert.is_nil(ok)
            assert.matches("not found", err)
        end)
    end)

    describe("renameColumn", function()
        it("should rename a column preserving type", function()
            writeTestFile(temp_dir, "test.tsv", "superType:type_spec\tname:string\nUnit\talpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:renameColumn("test.tsv", "superType", "parent")
            assert.is_true(ok)
            assert.is_true(ds:hasColumn("test.tsv", "parent"))
            assert.is_false(ds:hasColumn("test.tsv", "superType"))
            assert.are.equal("parent:type_spec", ds:getColumnSpec("test.tsv", "parent"))
            assert.are.equal("Unit", ds:getCell("test.tsv", "Unit", "parent"))
        end)

        it("should error on rename to existing column", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\nalpha\tAlice\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:renameColumn("test.tsv", "id", "name")
            assert.is_nil(ok)
            assert.matches("already exists", err)
        end)
    end)

    describe("moveColumn", function()
        it("should move a column to after another column", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\tparent:type_spec\nalpha\tAlice\tUnit\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:moveColumn("test.tsv", "parent", {after = "id"})
            assert.is_true(ok)
            local names = ds:getColumnNames("test.tsv")
            assert.same({"id", "parent", "name"}, names)
            -- Verify data moved correctly
            assert.are.equal("alpha", ds:getCell("test.tsv", "alpha", "id"))
            assert.are.equal("Unit", ds:getCell("test.tsv", "alpha", "parent"))
            assert.are.equal("Alice", ds:getCell("test.tsv", "alpha", "name"))
        end)

        it("should move a column to the beginning", function()
            writeTestFile(temp_dir, "test.tsv", "id:string\tname:string\tvalue:number\nalpha\tAlice\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:moveColumn("test.tsv", "value", {index = 1})
            local names = ds:getColumnNames("test.tsv")
            assert.same({"value", "id", "name"}, names)
        end)
    end)

    describe("setColumnType", function()
        it("should change the type in the column header", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tformat:string\nalpha\ttext\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:setColumnType("test.tsv", "format", "string|nil")
            assert.is_true(ok)
            assert.are.equal("format:string|nil", ds:getColumnSpec("test.tsv", "format"))
            assert.is_true(ds:isDirty("test.tsv"))
        end)
    end)

    describe("setColumnDefault", function()
        it("should set and remove a default value", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:setColumnDefault("test.tsv", "value", "0")
            assert.are.equal("value:number:0", ds:getColumnSpec("test.tsv", "value"))
            ds:setColumnDefault("test.tsv", "value", nil)
            assert.are.equal("value:number", ds:getColumnSpec("test.tsv", "value"))
        end)
    end)

    ---------------------------------------------------------------------------
    -- Row operations
    ---------------------------------------------------------------------------

    describe("rowCount", function()
        it("should count only data rows", function()
            writeTestFile(temp_dir, "test.tsv",
                "# comment\nname:string\n# section\nalpha\nbeta\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.are.equal(2, ds:rowCount("test.tsv"))
        end)
    end)

    describe("hasRow", function()
        it("should find rows by primary key", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\nbeta\t2\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.is_true(ds:hasRow("test.tsv", "alpha"))
            assert.is_true(ds:hasRow("test.tsv", "beta"))
            assert.is_false(ds:hasRow("test.tsv", "gamma"))
        end)
    end)

    describe("getRow", function()
        it("should return name→value table", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local row = ds:getRow("test.tsv", "alpha")
            assert.same({name = "alpha", value = "1"}, row)
        end)

        it("should error on missing row", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local row, err = ds:getRow("test.tsv", "missing")
            assert.is_nil(row)
            assert.matches("not found", err)
        end)
    end)

    describe("getRowByIndex", function()
        it("should return row by 1-based data index", function()
            writeTestFile(temp_dir, "test.tsv",
                "name:string\n# comment\nalpha\nbeta\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local row1 = ds:getRowByIndex("test.tsv", 1)
            assert.same({name = "alpha"}, row1)
            local row2 = ds:getRowByIndex("test.tsv", 2)
            assert.same({name = "beta"}, row2)
        end)

        it("should error on out-of-range index", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local row, err = ds:getRowByIndex("test.tsv", 99)
            assert.is_nil(row)
            assert.matches("out of range", err)
        end)
    end)

    describe("addRow", function()
        it("should append a row from a sequence", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:addRow("test.tsv", {"beta", "2"})
            assert.is_true(ok)
            assert.are.equal(2, ds:rowCount("test.tsv"))
            assert.are.equal("2", ds:getCell("test.tsv", "beta", "value"))
        end)

        it("should append a row from a name→value table", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:addRow("test.tsv", {name = "beta", value = "2"})
            assert.is_true(ok)
            assert.are.equal("2", ds:getCell("test.tsv", "beta", "value"))
        end)

        it("should error on duplicate primary key", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:addRow("test.tsv", {"alpha"})
            assert.is_nil(ok)
            assert.matches("duplicate", err)
        end)
    end)

    describe("removeRow", function()
        it("should remove a row by primary key", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\nbeta\t2\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:removeRow("test.tsv", "alpha")
            assert.is_true(ok)
            assert.are.equal(1, ds:rowCount("test.tsv"))
            assert.is_false(ds:hasRow("test.tsv", "alpha"))
            assert.is_true(ds:hasRow("test.tsv", "beta"))
        end)

        it("should error on missing row", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:removeRow("test.tsv", "missing")
            assert.is_nil(ok)
            assert.matches("not found", err)
        end)
    end)

    ---------------------------------------------------------------------------
    -- Cell operations
    ---------------------------------------------------------------------------

    describe("getCell / setCell", function()
        it("should get and set cell values", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.are.equal("1", ds:getCell("test.tsv", "alpha", "value"))
            local ok = ds:setCell("test.tsv", "alpha", "value", "42")
            assert.is_true(ok)
            assert.are.equal("42", ds:getCell("test.tsv", "alpha", "value"))
        end)

        it("should error on missing row", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local val, err = ds:getCell("test.tsv", "missing", "value")
            assert.is_nil(val)
            assert.matches("not found", err)
        end)

        it("should error on missing column", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local val, err = ds:getCell("test.tsv", "alpha", "missing")
            assert.is_nil(val)
            assert.matches("not found", err)
        end)
    end)

    describe("setCells", function()
        it("should set all cells in a column", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tparent:type_spec\nalpha\t\nbeta\t\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:setCells("test.tsv", "parent", "number")
            assert.is_true(ok)
            assert.are.equal("number", ds:getCell("test.tsv", "alpha", "parent"))
            assert.are.equal("number", ds:getCell("test.tsv", "beta", "parent"))
        end)
    end)

    describe("setCellsWhere", function()
        it("should set cells conditionally", function()
            writeTestFile(temp_dir, "test.tsv",
                "name:string\tsuperType:string\tstatus:string\n" ..
                "alpha\tType\tactive\n" ..
                "beta\tCustom\tactive\n" ..
                "gamma\tType\tinactive\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:setCellsWhere("test.tsv", "superType", "CustomType", "superType", "Type")
            assert.is_true(ok)
            assert.are.equal("CustomType", ds:getCell("test.tsv", "alpha", "superType"))
            assert.are.equal("Custom", ds:getCell("test.tsv", "beta", "superType"))
            assert.are.equal("CustomType", ds:getCell("test.tsv", "gamma", "superType"))
        end)
    end)

    describe("transformCells", function()
        it("should apply an expression to each cell", function()
            writeTestFile(temp_dir, "test.tsv",
                "name:string\tvalue:number\nalpha\t1\nbeta\t2\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:transformCells("test.tsv", "value",
                [[tostring(tonumber(value) * 10)]])
            assert.is_true(ok)
            assert.are.equal("10", ds:getCell("test.tsv", "alpha", "value"))
            assert.are.equal("20", ds:getCell("test.tsv", "beta", "value"))
        end)

        it("should provide row context", function()
            writeTestFile(temp_dir, "test.tsv",
                "name:string\tcategory:string\tprice:number\nalpha\trare\t10\nbeta\tcommon\t5\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:transformCells("test.tsv", "price",
                [[row.category == "rare" and tostring(tonumber(value) * 2) or value]])
            assert.is_true(ok)
            assert.are.equal("20", ds:getCell("test.tsv", "alpha", "price"))
            assert.are.equal("5", ds:getCell("test.tsv", "beta", "price"))
        end)

        it("should leave cell unchanged when expression returns nil", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:transformCells("test.tsv", "value", "nil")
            assert.is_true(ok)
            assert.are.equal("1", ds:getCell("test.tsv", "alpha", "value"))
        end)

        it("should report compile errors", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\tvalue:number\nalpha\t1\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:transformCells("test.tsv", "value", "!!! invalid syntax")
            assert.is_nil(ok)
            assert.matches("compile error", err)
        end)
    end)

    ---------------------------------------------------------------------------
    -- Comment / blank line operations
    ---------------------------------------------------------------------------

    describe("addComment", function()
        it("should insert a comment line", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\nbeta\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok = ds:addComment("test.tsv", "section marker", {afterRow = "alpha"})
            assert.is_true(ok)
            local raw = ds:getFile("test.tsv")
            -- Header at 1, alpha at 2, comment at 3, beta at 4
            assert.are.equal("# section marker", raw[3])
        end)

        it("should insert before header", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addComment("test.tsv", "preamble", {beforeHeader = true})
            local raw = ds:getFile("test.tsv")
            assert.are.equal("# preamble", raw[1])
            -- Header should have shifted to index 2
            assert.same({"name:string"}, raw[2])
        end)
    end)

    describe("addBlankLine", function()
        it("should insert a blank line", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addBlankLine("test.tsv", {afterHeader = true})
            local raw = ds:getFile("test.tsv")
            assert.are.equal("", raw[2])
        end)
    end)

    describe("removeLineAt / getRawLineCount / getRawLine", function()
        it("should manage raw lines", function()
            writeTestFile(temp_dir, "test.tsv", "# comment\nname:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.are.equal(3, ds:getRawLineCount("test.tsv"))
            assert.are.equal("# comment", ds:getRawLine("test.tsv", 1))
            assert.is_true(ds:isCommentLine("test.tsv", 1))
            -- Remove the comment
            ds:removeLineAt("test.tsv", 1)
            assert.are.equal(2, ds:getRawLineCount("test.tsv"))
        end)

        it("should not allow removing the header row", function()
            writeTestFile(temp_dir, "test.tsv", "name:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            local ok, err = ds:removeLineAt("test.tsv", 1) -- header is at index 1
            assert.is_nil(ok)
            assert.matches("cannot remove the header", err)
        end)
    end)

    describe("isCommentLine / isBlankLine", function()
        it("should identify comment and blank lines", function()
            writeTestFile(temp_dir, "test.tsv", "# comment\n\nname:string\nalpha\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            assert.is_true(ds:isCommentLine("test.tsv", 1))
            assert.is_false(ds:isCommentLine("test.tsv", 2))
            assert.is_true(ds:isBlankLine("test.tsv", 2))
            assert.is_false(ds:isBlankLine("test.tsv", 1))
        end)
    end)

    ---------------------------------------------------------------------------
    -- Files.tsv helper
    ---------------------------------------------------------------------------

    describe("filesHelper", function()
        local function setupFilesHelper()
            writeTestFile(temp_dir, "Files.tsv",
                "fileName:string\ttypeName:type_spec\tsuperType:super_type\tloadOrder:number\n" ..
                "CustomType.tsv\tCustomType\ttype\t50\n" ..
                "Unit.tsv\tUnit\tCustomType\t100\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("Files.tsv")
            return ds
        end

        it("should create a helper", function()
            local ds = setupFilesHelper()
            local fh, err = ds:filesHelper()
            assert.is_not_nil(fh)
            assert.is_nil(err)
        end)

        it("should update superType", function()
            local ds = setupFilesHelper()
            local fh = ds:filesHelper()
            fh:updateSuperType("CustomType.tsv", "custom_type_def")
            assert.are.equal("custom_type_def", ds:getCell("Files.tsv", "CustomType.tsv", "superType"))
        end)

        it("should update loadOrder", function()
            local ds = setupFilesHelper()
            local fh = ds:filesHelper()
            fh:updateLoadOrder("CustomType.tsv", "100")
            assert.are.equal("100", ds:getCell("Files.tsv", "CustomType.tsv", "loadOrder"))
        end)

        it("should update path (primary key)", function()
            local ds = setupFilesHelper()
            local fh = ds:filesHelper()
            fh:updatePath("Unit.tsv", "CustomType/Unit.tsv")
            -- After updating fileName (which is the primary key), lookup uses the new key
            assert.are.equal("CustomType/Unit.tsv",
                ds:getCell("Files.tsv", "CustomType/Unit.tsv", "fileName"))
            -- Old key should no longer exist
            assert.is_false(ds:hasRow("Files.tsv", "Unit.tsv"))
        end)

        it("should add and remove entries", function()
            local ds = setupFilesHelper()
            local fh = ds:filesHelper()
            fh:addEntry({"NewFile.tsv", "NewType", "type", "200"})
            assert.is_true(ds:hasRow("Files.tsv", "NewFile.tsv"))
            fh:removeEntry("NewFile.tsv")
            assert.is_false(ds:hasRow("Files.tsv", "NewFile.tsv"))
        end)

        it("should get an entry", function()
            local ds = setupFilesHelper()
            local fh = ds:filesHelper()
            local entry = fh:getEntry("CustomType.tsv")
            assert.are.equal("CustomType.tsv", entry.fileName)
            assert.are.equal("type", entry.superType)
        end)
    end)

    ---------------------------------------------------------------------------
    -- Manifest helper
    ---------------------------------------------------------------------------

    describe("manifestHelper", function()
        it("should get and set manifest fields", function()
            -- Create a transposed manifest
            writeTestFile(temp_dir, "Manifest.tsv",
                "key:string\tvalue:string\npackage_id\tmy_pkg\nversion\t1.0.0\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("Manifest.tsv")
            local mh = ds:manifestHelper("Manifest.tsv")
            assert.is_not_nil(mh)
            assert.are.equal("my_pkg", mh:getField("package_id"))
            assert.are.equal("1.0.0", mh:getField("version"))
            assert.are.equal("my_pkg", mh:getPackageId())
            assert.are.equal("1.0.0", mh:getVersion())
            mh:setField("version", "2.0.0")
            assert.are.equal("2.0.0", mh:getVersion())
        end)
    end)

    ---------------------------------------------------------------------------
    -- Round-trip tests
    ---------------------------------------------------------------------------

    describe("round-trip", function()
        it("should preserve data through load-modify-save-reload", function()
            writeTestFile(temp_dir, "test.tsv",
                "name:string\tvalue:number\nalpha\t1\nbeta\t2\n")
            local ds = data_set.new(temp_dir)
            ds:loadFile("test.tsv")
            ds:addColumn("test.tsv", "parent:type_spec|nil", {after = "name"})
            ds:setCells("test.tsv", "parent", "number")
            ds:setCell("test.tsv", "alpha", "value", "10")
            ds:saveFile("test.tsv")

            -- Reload in a new dataset
            local ds2 = data_set.new(temp_dir)
            ds2:loadFile("test.tsv")
            local names = ds2:getColumnNames("test.tsv")
            assert.same({"name", "parent", "value"}, names)
            assert.are.equal("number", ds2:getCell("test.tsv", "alpha", "parent"))
            assert.are.equal("10", ds2:getCell("test.tsv", "alpha", "value"))
            assert.are.equal("number", ds2:getCell("test.tsv", "beta", "parent"))
            assert.are.equal("2", ds2:getCell("test.tsv", "beta", "value"))
        end)
    end)
end)
