-- deserialization_spec.lua

-- Explicit requires for Busted functions and assertions
local busted = require("busted")
local assert = require("luassert")

-- Import the functions we'll use from busted
local describe = busted.describe
local it = busted.it

local deserialization = require("deserialization")

describe("deserialization", function()
  describe("deserialize (Lua literals)", function()
    it("should deserialize nil", function()
      local val, err = deserialization.deserialize("nil")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize empty string input as nil", function()
      local val, err = deserialization.deserialize("")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize booleans", function()
      local val, err = deserialization.deserialize("true")
      assert.is_true(val)
      assert.is_nil(err)

      val, err = deserialization.deserialize("false")
      assert.is_false(val)
      assert.is_nil(err)
    end)

    it("should deserialize integers", function()
      local val, err = deserialization.deserialize("42")
      assert.equals(42, val)
      assert.is_nil(err)

      val, err = deserialization.deserialize("-100")
      assert.equals(-100, val)
      assert.is_nil(err)

      val, err = deserialization.deserialize("0")
      assert.equals(0, val)
      assert.is_nil(err)
    end)

    it("should deserialize floats", function()
      local val, err = deserialization.deserialize("3.14")
      assert.equals(3.14, val)
      assert.is_nil(err)

      val, err = deserialization.deserialize("-2.5")
      assert.equals(-2.5, val)
      assert.is_nil(err)
    end)

    it("should deserialize strings", function()
      local val, err = deserialization.deserialize('"hello"')
      assert.equals("hello", val)
      assert.is_nil(err)

      val, err = deserialization.deserialize('"hello\\"world"')
      assert.equals('hello"world', val)
      assert.is_nil(err)
    end)

    it("should deserialize simple tables", function()
      local val, err = deserialization.deserialize("{1,2,3}")
      assert.is_nil(err)
      assert.are.same({1, 2, 3}, val)
    end)

    it("should deserialize tables with keys", function()
      local val, err = deserialization.deserialize('{a=1,b="test"}')
      assert.is_nil(err)
      assert.equals(1, val.a)
      assert.equals("test", val.b)
    end)

    it("should deserialize nested tables", function()
      local val, err = deserialization.deserialize('{1,{2,3},a={b="test"}}')
      assert.is_nil(err)
      assert.equals(1, val[1])
      assert.are.same({2, 3}, val[2])
      assert.equals("test", val.a.b)
    end)

    it("should deserialize tables with explicit numeric keys", function()
      local val, err = deserialization.deserialize('{[1]="a",[3]="c"}')
      assert.is_nil(err)
      assert.equals("a", val[1])
      assert.equals("c", val[3])
    end)

    it("should handle math.huge for infinity", function()
      local val, err = deserialization.deserialize("math.huge")
      assert.is_nil(err)
      assert.equals(math.huge, val)

      val, err = deserialization.deserialize("-math.huge")
      assert.is_nil(err)
      assert.equals(-math.huge, val)
    end)

    it("should return error for invalid Lua", function()
      local val, err = deserialization.deserialize("invalid lua code {{{")
      assert.is_nil(val)
      assert.is_not_nil(err)
    end)

    it("should return error for non-string input", function()
      local val, err = deserialization.deserialize(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)
  end)

  describe("deserializeJSON (typed JSON)", function()
    it("should deserialize null as nil", function()
      local val, err = deserialization.deserializeJSON("null")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize empty string input as nil", function()
      local val, err = deserialization.deserializeJSON("")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize booleans", function()
      local val, err = deserialization.deserializeJSON("true")
      assert.is_true(val)
      assert.is_nil(err)

      val, err = deserialization.deserializeJSON("false")
      assert.is_false(val)
      assert.is_nil(err)
    end)

    it("should deserialize integers with type wrapper", function()
      local val, err = deserialization.deserializeJSON('{"int":"42"}')
      assert.is_nil(err)
      assert.equals(42, val)
      assert.equals("integer", math.type(val))

      val, err = deserialization.deserializeJSON('{"int":"-100"}')
      assert.is_nil(err)
      assert.equals(-100, val)
    end)

    it("should deserialize strings", function()
      local val, err = deserialization.deserializeJSON('"hello"')
      assert.is_nil(err)
      assert.equals("hello", val)
    end)

    it("should deserialize special floats with type wrapper", function()
      local val, err = deserialization.deserializeJSON('{"float":"nan"}')
      assert.is_nil(err)
      assert.is_true(val ~= val)  -- NaN check

      val, err = deserialization.deserializeJSON('{"float":"inf"}')
      assert.is_nil(err)
      assert.equals(math.huge, val)

      val, err = deserialization.deserializeJSON('{"float":"-inf"}')
      assert.is_nil(err)
      assert.equals(-math.huge, val)
    end)

    it("should deserialize table encoding [size, elem1, ...]", function()
      -- Empty table
      local val, err = deserialization.deserializeJSON("[0]")
      assert.is_nil(err)
      assert.are.same({}, val)

      -- Sequence: [3, "a", "b", "c"]
      val, err = deserialization.deserializeJSON('[3,"a","b","c"]')
      assert.is_nil(err)
      assert.are.same({"a", "b", "c"}, val)
    end)

    it("should deserialize table with integers", function()
      local val, err = deserialization.deserializeJSON('[3,{"int":"1"},{"int":"2"},{"int":"3"}]')
      assert.is_nil(err)
      assert.are.same({1, 2, 3}, val)
    end)

    it("should deserialize map encoding [0, [key, val], ...]", function()
      local val, err = deserialization.deserializeJSON('[0,["a",{"int":"1"}]]')
      assert.is_nil(err)
      assert.equals(1, val.a)
    end)

    it("should deserialize mixed tables", function()
      -- [2, int1, int2, [key, val]]
      local val, err = deserialization.deserializeJSON('[2,{"int":"1"},{"int":"2"},["a","test"]]')
      assert.is_nil(err)
      assert.equals(1, val[1])
      assert.equals(2, val[2])
      assert.equals("test", val.a)
    end)

    it("should return error for invalid JSON", function()
      local val, err = deserialization.deserializeJSON("{invalid json")
      assert.is_nil(val)
      assert.is_not_nil(err)
    end)

    it("should return error for invalid int wrapper", function()
      local val, err = deserialization.deserializeJSON('{"int":"not_a_number"}')
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Failed to parse int", err)
    end)

    it("should return error for invalid float wrapper", function()
      local val, err = deserialization.deserializeJSON('{"float":"not_a_float"}')
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Failed to parse float", err)
    end)

    it("should return error for bad key-value pair in table", function()
      -- Table format expects key-value pairs as [key, val] arrays of length 2
      -- Here we have an array of length 1 instead of 2
      local val, err = deserialization.deserializeJSON('[0,["only_key"]]')
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Bad JSON format", err)
    end)

    it("should return error for bad key-value pair - not an array", function()
      -- Key-value pair should be an array [key, val], not a scalar
      local val, err = deserialization.deserializeJSON('[0,"not_an_array"]')
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Bad JSON format", err)
    end)

    it("should return error for non-string input", function()
      local val, err = deserialization.deserializeJSON(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)
  end)

  describe("deserializeNaturalJSON", function()
    it("should deserialize null as nil", function()
      local val, err = deserialization.deserializeNaturalJSON("null")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize booleans", function()
      local val, err = deserialization.deserializeNaturalJSON("true")
      assert.is_true(val)
      assert.is_nil(err)
    end)

    it("should deserialize numbers", function()
      local val, err = deserialization.deserializeNaturalJSON("42")
      assert.is_nil(err)
      assert.equals(42, val)

      val, err = deserialization.deserializeNaturalJSON("3.14")
      assert.is_nil(err)
      assert.equals(3.14, val)
    end)

    it("should deserialize strings", function()
      local val, err = deserialization.deserializeNaturalJSON('"hello"')
      assert.is_nil(err)
      assert.equals("hello", val)
    end)

    it("should deserialize special float strings", function()
      local val, err = deserialization.deserializeNaturalJSON('"NAN"')
      assert.is_nil(err)
      assert.is_true(val ~= val)  -- NaN check

      val, err = deserialization.deserializeNaturalJSON('"INF"')
      assert.is_nil(err)
      assert.equals(math.huge, val)

      val, err = deserialization.deserializeNaturalJSON('"-INF"')
      assert.is_nil(err)
      assert.equals(-math.huge, val)
    end)

    it("should deserialize arrays", function()
      local val, err = deserialization.deserializeNaturalJSON('[1,2,3]')
      assert.is_nil(err)
      assert.are.same({1, 2, 3}, val)
    end)

    it("should deserialize objects", function()
      local val, err = deserialization.deserializeNaturalJSON('{"a":1,"b":"test"}')
      assert.is_nil(err)
      assert.equals(1, val.a)
      assert.equals("test", val.b)
    end)

    it("should deserialize nested structures", function()
      local val, err = deserialization.deserializeNaturalJSON('{"outer":{"inner":"value"}}')
      assert.is_nil(err)
      assert.equals("value", val.outer.inner)
    end)

    it("should convert numeric string keys back to numbers", function()
      local val, err = deserialization.deserializeNaturalJSON('{"1":"a","2":"b"}')
      assert.is_nil(err)
      assert.equals("a", val[1])
      assert.equals("b", val[2])
    end)

    it("should return error for invalid JSON", function()
      local val, err = deserialization.deserializeNaturalJSON("{invalid json")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Failed to parse JSON", err)
    end)

    it("should return error for non-string input", function()
      local val, err = deserialization.deserializeNaturalJSON(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)
  end)

  describe("deserializeXML", function()
    it("should deserialize <null/>", function()
      local val, _pos, err = deserialization.deserializeXML("<null/>")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize empty string input as nil", function()
      local val, _pos, err = deserialization.deserializeXML("")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize booleans", function()
      local val, _pos, err = deserialization.deserializeXML("<true/>")
      assert.is_true(val)
      assert.is_nil(err)

      val, _pos, err = deserialization.deserializeXML("<false/>")
      assert.is_false(val)
      assert.is_nil(err)
    end)

    it("should deserialize integers", function()
      local val, _pos, err = deserialization.deserializeXML("<integer>42</integer>")
      assert.is_nil(err)
      assert.equals(42, val)
      assert.equals("integer", math.type(val))
    end)

    it("should deserialize floats", function()
      local val, _pos, err = deserialization.deserializeXML("<number>3.14</number>")
      assert.is_nil(err)
      assert.equals(3.14, val)
    end)

    it("should deserialize special floats", function()
      local val, _pos, err = deserialization.deserializeXML("<number>nan</number>")
      assert.is_nil(err)
      assert.is_true(val ~= val)  -- NaN check

      val, _pos, err = deserialization.deserializeXML("<number>inf</number>")
      assert.is_nil(err)
      assert.equals(math.huge, val)

      val, _pos, err = deserialization.deserializeXML("<number>-inf</number>")
      assert.is_nil(err)
      assert.equals(-math.huge, val)
    end)

    it("should deserialize strings", function()
      local val, _pos, err = deserialization.deserializeXML("<string>hello</string>")
      assert.is_nil(err)
      assert.equals("hello", val)
    end)

    it("should deserialize empty strings", function()
      local val, _pos, err = deserialization.deserializeXML("<string/>")
      assert.is_nil(err)
      assert.equals("", val)
    end)

    it("should unescape XML entities in strings", function()
      local val, _pos, err = deserialization.deserializeXML("<string>&lt;tag&gt;&amp;&quot;test&apos;</string>")
      assert.is_nil(err)
      assert.equals('<tag>&"test\'', val)
    end)

    it("should deserialize sequence tables", function()
      local val, _pos, err = deserialization.deserializeXML("<table><integer>1</integer><integer>2</integer><integer>3</integer></table>")
      assert.is_nil(err)
      assert.are.same({1, 2, 3}, val)
    end)

    it("should deserialize map tables with key_value", function()
      local val, _pos, err = deserialization.deserializeXML("<table><key_value><string>a</string><integer>1</integer></key_value></table>")
      assert.is_nil(err)
      assert.equals(1, val.a)
    end)

    it("should deserialize mixed tables", function()
      local val, _pos, err = deserialization.deserializeXML("<table><integer>1</integer><integer>2</integer><key_value><string>a</string><string>test</string></key_value></table>")
      assert.is_nil(err)
      assert.equals(1, val[1])
      assert.equals(2, val[2])
      assert.equals("test", val.a)
    end)

    it("should deserialize nested tables", function()
      local val, _pos, err = deserialization.deserializeXML("<table><table><integer>1</integer><integer>2</integer></table></table>")
      assert.is_nil(err)
      assert.are.same({{1, 2}}, val)
    end)

    it("should return error for non-string input", function()
      local val, _pos, err = deserialization.deserializeXML(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)

    it("should return error for unexpected end of XML", function()
      local val, _pos, err = deserialization.deserializeXML("   ")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Unexpected end of XML", err)
    end)

    it("should return error for missing opening tag", function()
      local val, _pos, err = deserialization.deserializeXML("not a tag")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Expected '<'", err)
    end)

    it("should return error for malformed tag", function()
      local val, _pos, err = deserialization.deserializeXML("<malformed")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Malformed tag", err)
    end)

    it("should return error for unknown self-closing tag", function()
      local val, _pos, err = deserialization.deserializeXML("<unknown_tag/>")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Unknown self%-closing tag", err)
    end)

    it("should return error for unclosed tag", function()
      -- Note: "<integer" triggers "Malformed tag" because there's no closing ">"
      -- A true "Unclosed tag" would be "<integer>" without closing "</integer>"
      local val, _pos, err = deserialization.deserializeXML("<integer")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Malformed tag", err)
    end)

    it("should return error for tag with missing close bracket", function()
      local val, _pos, err = deserialization.deserializeXML("<integer 42")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Unclosed tag", err)
    end)

    it("should return error for missing closing integer tag", function()
      local val, _pos, err = deserialization.deserializeXML("<integer>42")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for integer", err)
    end)

    it("should return error for missing closing number tag", function()
      local val, _pos, err = deserialization.deserializeXML("<number>3.14")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for number", err)
    end)

    it("should return error for missing closing string tag", function()
      local val, _pos, err = deserialization.deserializeXML("<string>hello")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for string", err)
    end)

    it("should return error for missing closing table tag", function()
      local val, _pos, err = deserialization.deserializeXML("<table><integer>1</integer>")
      assert.is_nil(val)
      assert.is_not_nil(err)
      -- Table parsing continues until it finds closing tag or errors
    end)

    it("should return error for missing closing key_value tag", function()
      local val, _pos, err = deserialization.deserializeXML("<table><key_value><string>key</string><integer>1</integer></table>")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Expected </key_value>", err)
    end)

    it("should return error for unknown tag type", function()
      local val, _pos, err = deserialization.deserializeXML("<foobar>content</foobar>")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Unknown tag", err)
    end)

    it("should return error for missing closing null tag", function()
      local val, _pos, err = deserialization.deserializeXML("<null>content")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for null", err)
    end)

    it("should return error for missing closing true tag", function()
      local val, _pos, err = deserialization.deserializeXML("<true>content")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for true", err)
    end)

    it("should return error for missing closing false tag", function()
      local val, _pos, err = deserialization.deserializeXML("<false>content")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for false", err)
    end)

    it("should return error for missing closing function tag", function()
      local val, _pos, err = deserialization.deserializeXML("<function>content")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Missing closing tag for function", err)
    end)
  end)

  describe("deserializeMessagePack", function()
    local mpk = require("MessagePack")

    it("should deserialize nil", function()
      local packed = mpk.pack(nil)
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should deserialize booleans", function()
      local packed = mpk.pack(true)
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_true(val)
      assert.is_nil(err)
    end)

    it("should deserialize numbers", function()
      local packed = mpk.pack(42)
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_nil(err)
      assert.equals(42, val)
    end)

    it("should deserialize strings", function()
      local packed = mpk.pack("hello")
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_nil(err)
      assert.equals("hello", val)
    end)

    it("should deserialize tables", function()
      local packed = mpk.pack({1, 2, 3})
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_nil(err)
      assert.are.same({1, 2, 3}, val)
    end)

    it("should deserialize nested tables", function()
      local packed = mpk.pack({a = {b = {c = 1}}})
      local val, err = deserialization.deserializeMessagePack(packed)
      assert.is_nil(err)
      assert.equals(1, val.a.b.c)
    end)

    it("should return error for empty string", function()
      local val, err = deserialization.deserializeMessagePack("")
      assert.is_nil(val)
      assert.is_nil(err)
    end)

    it("should return error for non-string input", function()
      local val, err = deserialization.deserializeMessagePack(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)

    it("should return error for invalid MessagePack data", function()
      local val, err = deserialization.deserializeMessagePack("\xFF\xFF\xFF")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Failed to unpack MessagePack", err)
    end)
  end)

  describe("deserializeSQLBlob", function()
    it("should deserialize empty blob", function()
      local val, err = deserialization.deserializeSQLBlob("X''")
      assert.is_nil(err)
      assert.equals("", val)
    end)

    it("should deserialize hex blob", function()
      local val, err = deserialization.deserializeSQLBlob("X'48656C6C6F'")
      assert.is_nil(err)
      assert.equals("Hello", val)
    end)

    it("should handle all byte values", function()
      local val, err = deserialization.deserializeSQLBlob("X'00FF'")
      assert.is_nil(err)
      assert.equals("\x00\xFF", val)
    end)

    it("should return error for invalid format", function()
      local val, err = deserialization.deserializeSQLBlob("invalid")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Invalid SQL BLOB format", err)
    end)

    it("should return error for missing X prefix", function()
      local val, err = deserialization.deserializeSQLBlob("'48656C6C6F'")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Invalid SQL BLOB format", err)
    end)

    it("should return error for missing quotes", function()
      local val, err = deserialization.deserializeSQLBlob("X48656C6C6F")
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("Invalid SQL BLOB format", err)
    end)

    it("should return error for non-string input", function()
      local val, err = deserialization.deserializeSQLBlob(123)
      assert.is_nil(val)
      assert.is_not_nil(err)
      assert.matches("not a string", err)
    end)
  end)

  describe("deserializeMessagePackSQLBlob", function()
    local serialization = require("serialization")

    it("should round-trip through SQL BLOB", function()
      local original = {foo = "bar", num = 42}
      local blob = serialization.serializeMessagePackSQLBlob(original)
      local val, err = deserialization.deserializeMessagePackSQLBlob(blob)
      assert.is_nil(err)
      assert.are.same(original, val)
    end)
  end)

  describe("module API", function()
    describe("getVersion", function()
      it("should return a version string", function()
        local version = deserialization.getVersion()
        assert.is_string(version)
        assert.matches("^%d+%.%d+%.%d+$", version)
      end)
    end)

    describe("callable API", function()
      it("should return version when called with 'version'", function()
        local version = deserialization("version")
        assert.is_not_nil(version)
        assert.are.equal(deserialization.getVersion(), tostring(version))
      end)

      it("should call API functions when called with function name", function()
        local result = deserialization("deserialize", "42")
        assert.are.equal(42, result)
      end)

      it("should error on unknown operation", function()
        assert.has_error(function()
          deserialization("nonexistent_operation")
        end, "Unknown operation: nonexistent_operation")
      end)
    end)

    describe("__tostring", function()
      it("should return module name and version", function()
        local str = tostring(deserialization)
        assert.is_string(str)
        assert.matches("^deserialization version %d+%.%d+%.%d+$", str)
      end)
    end)
  end)
end)
